[project]
name = "unibot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aws-cdk-lib==2.144.0",
    "boto3>=1.40.42",
    "bs4>=0.0.2",
    "constructs>=10.0.0,<11.0.0",
    "langchain-aws>=0.2.34",
    "langchain-community>=0.3.30",
    "langchain-core>=0.3.77",
    "langchain-openai>=0.3.34",
    "langchain-pinecone>=0.2.12",
    "lxml>=6.0.2",
    "pinecone>=7.3.0",
    "pydantic>=2.11.9",
    "pynacl>=1.6.0",
    "python-dotenv>=1.1.1",
    "pyyaml>=6.0.3",
    "requests>=2.32.5",
]
