# Data vault

# Departments
class DEPARTMENT_CODES:
    ACCOUNTING = "LACCOUNT"
    AMERICAN_STUDIES = "LAMERSTDY"
    ART_AND_DESIGN = "LAESTCRSTY|LFINEARTS|LSTUDIOART"
    ART_HISTORY = "LARTHISTRY"
    BIOLOGY = "LBIOLOGY"
    # BIOMEDICAL_AND_NUTRICIAN

# Course Prefixes 
DEPARTMENT_PREFIXES = [
    "ACCT",
    "AERO",
    "AEST",
    "AMHE",
    "AMST",
    "ARCH",
    "ARHI",
    "ARTS",
    "ASAM",
    "ATMO",
    "BIOL",
    "BMBT",
    "BMEN",
    "BMSC",
    "BOST",
    "BUSI",
    "CHEM",
    "CHEN",
    "CIVE",
    "COMP",
    "CONT",
    "CORE",
    "CRIM",
    "DART",
    "DGMD",
    "DPTH",
    "ECON",
    "EDUC",
    "EECE",
    "ENGL",
    "ENGN",
    "ENGY",
    "ENTR",
    "ENVE",
    "ENVI",
    "ENVS",
    "ETEC",
    "EXER",
    "FAHS",
    "FINA",
    "GEOL",
    "GLST",
    "GNDR",
    "GRFX",
    "HIST",
    "HONR",
    "HSCI",
    "IENG",
    "IM",
    "INFO",
    "LABR",
    "LGST",
    "LIFE",
    "LMUCM",
    "MARI",
    "MATH",
    "MECH",
    "MGMT",
    "MIST",
    "MKTG",
    "MLSC",
    "MPAD",
    "MSIT",
    "MTEC",
    "MUAP",
    "MUBU",
    "MUCM",
    "MUED",
    "MUEN",
    "MUHI",
    "MUPF",
    "MUSR",
    "MUTH",
    "NONC",
    "NURS",
    "NUTR",
    "PCST",
    "PHIL",
    "PHRM",
    "PHYS",
    "PLAS",
    "POLI",
    "POLY",
    "POMS",
    "PSMA",
    "PSYC",
    "PTEC",
    "PUBH",
    "RADI",
    "ROTC",
    "SCIE",
    "SOCI",
    "THEA",
    "UGTC",
    "UMLO",
    "UNCR",
    "UTCH",
    "WLAN",
    "WLAR",
    "WLCH",
    "WLFR",
    "WLGE",
    "WLIT",
    "WLKH",
    "WLLA",
    "WLPO",
    "WLSP",
    "WORC",
]

# College Suffixes
class COLLEGE_CODES:
    COLLEGE_EDUCATION = "EDGR"
    COLLEGE_ENGINEERING = "EN"
    COLLEGE_ARTS = "A&S"
    COLLEGE_HEALTH = "HP"
    COLLEGE_SCIENCES = "SCI"
    COLLEGE_BUSINESS = "MG"

COLLEGES = {
    COLLEGE_CODES.COLLEGE_EDUCATION: "College of Education",
    COLLEGE_CODES.COLLEGE_ENGINEERING: "Francis College of Engineering",
    COLLEGE_CODES.COLLEGE_ARTS: "College of Fine Arts, Humanities, and Social Sciences",
    COLLEGE_CODES.COLLEGE_HEALTH: "Zuckerberg College of Health Sciences",
    COLLEGE_CODES.COLLEGE_SCIENCES: "Kennedy College of Sciences",
    COLLEGE_CODES.COLLEGE_BUSINESS: "Manning School of Business",
}
