name: Update Vector Index

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install dependencies
              run: |
                pip install -r requirements.txt

            - name: Import Vector Index
              run: python3 data/main.py --importdata
              env:
                PINECONE_API_KEY: ${{secrets.PINECONE_API_KEY}}
                PINECONE_INDEX_NAME: ${{vars.PINECONE_INDEX_NAME}}
                APP_NAME: ${{vars.APP_NAME}}
                OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
