name: Update Vector Index

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs at midnight on the first day of every month
  workflow_dispatch:  # Allows manual triggering

jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install dependencies
              run: |
                pip install -r requirements.txt

            - name: Update Vector Index
              run: python3 data/main.py
              env:
                PINECONE_API_KEY: ${{secrets.PINECONE_API_KEY}}
                PINECONE_INDEX_NAME: ${{vars.PINECONE_INDEX_NAME}}
                APP_NAME: ${{vars.APP_NAME}}
                OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}

            - name: Update Course Index
              run: python3 data/main.py --courses
              env:
                PINECONE_API_KEY: ${{secrets.PINECONE_API_KEY}}
                PINECONE_INDEX_NAME: ${{vars.PINECONE_INDEX_NAME}}
                APP_NAME: ${{vars.APP_NAME}}
                OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v6
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                commit-message: Automatic Vector Database Content Update
                title: Update Vector Index
                body: Update Vector Index
                branch: database-update
                base: main
