name: Update Discord Commands

on:
  push:
    branches:
      - main  # Specifies that this workflow should only run on the main branch
    paths:
      - 'discord_commands.yaml'

jobs:
  update-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ github.workspace }}/commands/requirements.txt
      
      - name: Run register_commands.py
        run: python ${{ github.workspace }}/commands/register_commands.py
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}